# Generated by Django 4.2.1 on 2023-05-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Название категории"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL категории")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Название"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL продукта")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="В наличии"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(verbose_name="Количество товара"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("create_time", "name"),
                "index_together": {("id", "slug")},
            },
        ),
    ]
