# Generated by Django 4.2.1 on 2023-06-18 20:33

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                validators=[main.validators.price_validate], verbose_name="Цена"
            ),
        ),
    ]
