# Generated by Django 4.2.1 on 2023-05-31 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        upload_to="media/profile_photos/%Y/%m/%d",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Профиль",
                    ),
                ),
            ],
        ),
    ]
