# Generated by Django 4.2.1 on 2023-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_options_alter_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
