# Generated by Django 4.2.1 on 2023-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
