# Generated by Django 4.2.1 on 2023-06-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Stripe ID"
            ),
        ),
    ]
