# Generated by Django 4.2.1 on 2023-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_cost",
            field=models.PositiveIntegerField(default=0, verbose_name="Общая сумма"),
        ),
    ]
