# Generated by Django 4.2.1 on 2023-06-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_orderitem_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                default="Не указано", max_length=255, verbose_name="Адрес"
            ),
        ),
    ]
