# Generated by Django 4.2.1 on 2023-06-01 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Товар заказа",
                "verbose_name_plural": "Товары заказа",
            },
        ),
    ]
